json.id @user.id
json.buying_power_available @user.buying_power_available
json.total_market_value @user.total_market_value
json.shares_owned @user.shares_owned
json.intraday_data @user.intraday_data
json.weekly_data @user.weekly_data
json.monthly_data @user.monthly_data
json.three_month_data @user.three_month_data
json.yearly_data @user.yearly_data
json.five_year_data @user.five_year_data
json.current_stock_prices @user.current_stock_prices
